# Main Menu

MAIN_MENU_JOUEUR = "1"
MAIN_MENU_TOUNOI = "2"
MAIN_MENU_REPORTS = "3"
MAIN_MENU_QUIT = "0"

# Player Menu

PLAYER_MENU_NOUVEAU = "1"
PLAYER_MENU_AFFICHER = "2"
PLAYER_MENU_QUIT = "0"

# Dossier et Nom fichier

DATA_FOLDER = "data"
REPORTS_FOLDER = "reports"
FILE_NAME = "players.json"
FILE_NAME2 = "tournament.json"
TEMPLATES = "templates/template.html"
TEMPLATES_LIST_TOURNAMENT = "templates/template_list_tournament.html"
TEMPLATES_DETAILS = "templates/template_details_tournament.html"
TEMPLATES_DATE = "templates/template_date_tournament.html"

# Tournament Menu

TOURNAMENT_MENU_NOUVEAU = "1"
TOURNAMENT_MENU_AFFICHER = "2"
TOURNAMENT_MENU_LANCER = "3"
TOURNAMENT_MENU_REPRENDRE = "4"
TOURNAMENT_MENU_QUIT = "0"

# Etat tournoi

TO_LAUNCH = "TO LAUNCH"
IN_PROGRESS = "IN PROGRESS"
FINISH = "FINISH"

# Report Menu

REPORT_MENU_LISTE_JOUEUR_ALPHA = "1"
REPORT_MENU_LISTE_TOURNOI = "2"
REPORT_MENU_LISTE_DATE_TOURNOI = "3"
REPORT_MENU_LISTE_JOUEUR_TOURNOI = "4"
REPORT_MENU_LISTE_ROUND_MATCH_TOURNOI = "5"
REPORT_MENU_QUIT = "0"
