
MAIN_MENU_JOUEUR = "1"
MAIN_MENU_TOUNOI = "2"
MAIN_MENU_REPORTS = "3"
MAIN_MENU_QUIT = "4"

# Player Menu
PLAYER_MENU_NOUVEAU = "1"
PLAYER_MENU_AFFICHER = "2"
PLAYER_MENU_QUIT = "3"

# Dossier et Nom fichier
DATA_FOLDER = 'data'
FILE_NAME = "players.json"
FILE_NAME2 = "tournament.json"

# Tournament Menu
TOURNAMENT_MENU_NOUVEAU = "1"
TOURNAMENT_MENU_AFFICHER = "2"
TOURNAMENT_MENU_LANCER = "3"
TOURNAMENT_MENU_REPRENDRE = "4"
TOURNAMENT_MENU_QUIT = "5"

# Etat tournoi
TO_LAUNCH = "TO LAUNCH"
IN_PROGRESS = "IN PROGRESS"
FINISH = "FINISH"
