
def Menu ():
    ascii_art = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'    .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'        .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'            .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'                .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'        .:c'        .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'         ,ONW0;         .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx,         .l0WMMW0o.         .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMXx,           .oKWMMWKd.           .oKWMMMMMMMMMMMMMMMMMMWWMMMMMMMMMM
MMMMMMMMWKo:dXMMMMMMMMMMMMMMMXx,              .lNMMNo.              .oKWMMMMMMMMMMMMMMNxcl0WMMMMMMMM
MMMMMMWKo.   'dXMMMMMMMMMMMXx,             .lxx0WMMWKxdo.             .oKWMMMMMMMMMMNx,   .l0WMMMMMM
MMMMMXo.       'dXMMMMMMMXx,               .kWMMMMMMMMWO'               .oKWMMMMMMNx,       .lKWMMMM
MMWXo.           'dXMMMXx,                  ,0MMMMMMMM0;                  .oXWMMNx,           .lKWMM
MXd'               'd0x,                     :XMMMMMMXc                     .o0x,               .lKW
M0:                .:kc.                     .kMMMMMMO.                      :xl.                ,OW
MMNk,             ;kNMWO:.                  'oXMMMMMMXd'                   ,xNMWOc.            'dXMM
MMMMNx,         ;kNMMMMMWO:.                ;xXMMMMMMXx;                 ,xNMMMMMWO:.        'dXWMMM
MMMMMMNx,     ;kNMMMMMMMMMNO:.               .dWMMMMWx.                ,xNMMMMMMMMMWO:.    'dXMMMMMM
MMMMMMMMNx,.;kNMMMMMMMMMMMMMNO:.              cNMMMMNl               ,xNMMMMMMMMMMMMMWO:.'dXMMMMMMM
MMMMMMMMMXl'oXMMMMMMMMMMMMMMMNd.              :XMMMMNc              .lXMMMMMMMMMMMMMMMNd':KWMMMMMMMM
MMMMMMMXd'   ,xXMMMMMMMMMMMNx,                cXMMMMNc                'dXMMMMMMMMMMMNk;   .oKWMMMMMM
MMMMMXd'       ,xXMMMMMMMNx,                  cNMMMMNl                  'dXMMMMMMMNk;       .oKWMMMM
MMMXd'           ,xXMMMNx,                   .dWMMMMWx.                   'dXMMMNk;           .oKWMM
MXd'               ,xKx,                     'OMMMMMM0,                     'd0k;               .oKM
M0;                 :xc.                     lNMMMMMMNo                      ;xl.                'kW
MMNx,             ,xNMNk;                   ,0MMMMMMMM0;                   ,xXMWO:.            'oKWM
MMMMNx,         ,xNMMMMMNk;                :KWMMMMMMMMWKc                ,xXMMMMMNO:.        .oKWMMM
MMMMMMXx,     ,xNMMMMMMMMMNk;            .lXMMMMMMMMMMMMXo.            ,xXMMMMMMMMMWO:.    .oXWMMMMM
MMMMMMMMXx,.,xNMMMMMMMMMMMMMNk;         ,OWMMMMMMMMMMMMMMW0,         ,xXMMMMMMMMMMMMMNO:.'oKWMMMMMMM
MMMMMMMMMMXKNMMMMMMMMMMMMMMMMMNk;       ,0WMMMMMMMMMMMMMMM0;       ,xXMMMMMMMMMMMMMMMMMNKXWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;     .l0KKKKKKKKKKKKKK0o.     ,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;     ................     ,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;                      'xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,                  'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;              'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,          'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,      'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,..'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""
    print(ascii_art)
    while True:
     print("\nMenu :")
     print("1. Gestion des joueurs")
     print("2. Gestion des tournois")
     print("3. Rapports")
     print("4. Quitter")
     choice = input("Choisissez une option : ")
     
     if choice == "1":
        pass
     elif choice == "2":
        pass
     elif choice == "3":
         pass
     elif choice == "4":
         print("Au revoir !")
         break           
     else:
      print("Option invalide. Veuillez choisir une option valide.")

